#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the narrow variants that `srcset` needs.

WHY. Every rendered image on the site ships at one size — usually 960px wide —
whatever the space it is drawn in. Lighthouse costed that at 356 KB on the home
page, 399 KB on Seminarios and 418 KB in the gallery: a phone downloading a
960px poster to paint it 320px wide.

This writes `-480` and `-800` variants beside every rendered WebP wider than
560px. The threshold was 900, which left the portrait social images — 720px
wide, drawn at about 240 — with nothing to offer: 67 KB of waste on the gallery
by Lighthouse's count, on a page where nothing else was left to cut. The templates then offer all three through `srcset` and let the browser
pick, which is the only mechanism that gets this right across every viewport
and pixel density.

It also writes `_data/imgw.yml`, and that half is not optional. The templates
used to spell the srcset out by hand — `-480 480w, -800 800w, .webp 960w` — for
every image alike, which was wrong twice over. Sources narrower than 900px get
no variants (there is nothing to save), so half the URLs in those srcsets were
404s: 374 of the 666 referenced, logged as console errors on every gallery and
seminar page. And `960w` was a constant, so a 600px original was advertised as
960px and the browser picked it for slots it could not fill.

The map holds one ready-made srcset per image, listing only files that exist
and only widths that are true. A template looks its image up and prints what
comes back, or no srcset at all. `tools/qa.py` checks every referenced variant
resolves, so this cannot rot again.

It is the same idea as tools/gallery-thumbs.py, which already took Ura's
contact sheet from 2.4 MB to 310 KB; this is that applied to the rest.

    python3 tools/image-widths.py           # write what is missing
    python3 tools/image-widths.py --force   # rewrite everything

Run it after adding images, then build again so the map reaches the pages.

Needs `cwebp` (brew install webp). Not a project dependency: it runs when
images change, which is rarely, and never on a build.
"""
import glob
import os
import re
import subprocess
import sys

WIDTHS = (480, 800)
MIN_SOURCE = 560          # below this there is nothing worth saving
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES = os.path.join(ROOT, 'images')


def rendered():
    """Only images the built site actually references — not every file on disk."""
    site = os.path.join(ROOT, '_site')
    if not os.path.isdir(site):
        sys.exit('no _site — run `npx gulp build` first')
    used = set()
    for f in glob.glob(os.path.join(site, '**', '*.html'), recursive=True):
        for m in re.finditer(r'/images/([^"\'\s]+\.webp)', open(f, encoding='utf-8').read()):
            used.add(m.group(1))
    return sorted(used)


def size_of(path):
    out = subprocess.run(['file', path], capture_output=True, text=True).stdout
    m = re.search(r'(\d+)x(\d+)', out)
    return (int(m.group(1)), int(m.group(2))) if m else (0, 0)


def width_of(path):
    return size_of(path)[0]


def write_map():
    """One srcset per image, naming only files that exist at widths that are true.

    Keyed by basename without extension, which is what the templates carry.
    Every image on disk is considered, not only the rendered ones: a map that
    depended on _site would need two builds to settle after a page starts
    showing an image it did not show before.
    """
    rows = []
    for src in sorted(glob.glob(os.path.join(IMAGES, '*.webp'))):
        name = os.path.basename(src)[:-5]
        if re.search(r'-(?:\d{3,4}|t)$', name):
            continue
        w = width_of(src)
        if not w:
            continue
        cand = [('/images/%s-%d.webp' % (name, t), t) for t in WIDTHS
                if os.path.exists(os.path.join(IMAGES, '%s-%d.webp' % (name, t)))]
        if not cand:
            continue                      # no variants, so no srcset to offer
        cand.append(('/images/%s.webp' % name, w))
        rows.append('%s: "%s"' % (yaml_key(name),
                                  ', '.join('%s %dw' % c for c in cand)))
    out = os.path.join(ROOT, '_data', 'imgw.yml')
    body = ('# Generated by tools/image-widths.py — do not edit.\n'
            '# One srcset per image: only files that exist, only widths that are true.\n'
            + '\n'.join(rows) + '\n')
    old = open(out, encoding='utf-8').read() if os.path.exists(out) else None
    open(out, 'w', encoding='utf-8').write(body)
    print('  _data/imgw.yml: %d images with variants%s'
          % (len(rows), '' if old == body else '  (changed — rebuild)'))


def write_dims():
    """Intrinsic pixel size per image, for `width`/`height` on the <img>.

    The seminar and elsewhere cards used to hardcode `width="640" height="905"`
    because every poster the dojo prints is drawn to that A-series ratio. The
    Elsewhere page shows other people's posters, and they are 1:1, 4:5, 2:3 and
    three other things besides. A hardcoded ratio there is a wrong aspect-ratio
    box, which is a layout shift on every card as each image arrives.

    Same principle as imgw.yml: the number is read off the file rather than
    typed, so it cannot be wrong and cannot drift.
    """
    rows = []
    for src in sorted(glob.glob(os.path.join(IMAGES, '*.webp'))):
        name = os.path.basename(src)[:-5]
        if re.search(r'-(?:\d{3,4}|t)$', name):
            continue
        w, h = size_of(src)
        if not w or not h:
            continue
        rows.append('%s: [%d, %d]' % (yaml_key(name), w, h))
    out = os.path.join(ROOT, '_data', 'imgdim.yml')
    body = ('# Generated by tools/image-widths.py — do not edit.\n'
            '# The intrinsic size of every image: [width, height].\n'
            + '\n'.join(rows) + '\n')
    old = open(out, encoding='utf-8').read() if os.path.exists(out) else None
    open(out, 'w', encoding='utf-8').write(body)
    print('  _data/imgdim.yml: %d images%s'
          % (len(rows), '' if old == body else '  (changed — rebuild)'))


def yaml_key(name):
    """Quote anything YAML could read as something other than a string."""
    return '"%s"' % name if re.match(r'^[\d.+-]|[:#{}\[\],&*?|<>=!%@`\'"]', name) else name


def main():
    force = '--force' in sys.argv
    if subprocess.call(['which', 'cwebp'], stdout=subprocess.DEVNULL):
        sys.exit('cwebp not found — brew install webp')

    made = skipped = small = 0
    saved = 0
    for name in rendered():
        # never make variants of a variant
        if re.search(r'-(?:\d{3,4}|t)\.webp$', name):
            continue
        src = os.path.join(IMAGES, name)
        if not os.path.exists(src):
            continue
        w = width_of(src)
        if w < MIN_SOURCE:
            small += 1
            continue
        for target in WIDTHS:
            if target >= w:
                continue
            dst = src[:-5] + '-%d.webp' % target
            if os.path.exists(dst) and not force:
                skipped += 1
                continue
            r = subprocess.run(['cwebp', '-quiet', '-q', '80', '-resize', str(target), '0',
                                src, '-o', dst], capture_output=True)
            if r.returncode:
                continue
            made += 1
            saved += os.path.getsize(src) - os.path.getsize(dst)

    print('  %d variants written, %d already there, %d sources below %dpx'
          % (made, skipped, small, MIN_SOURCE))
    write_map()
    write_dims()
    if made:
        print('  %.1f MB lighter than serving the original at those sizes'
              % (saved / 1024 / 1024))


if __name__ == '__main__':
    main()
