# -*- coding: utf-8 -*-
"""Glosario — aikido, artes marciales y japonés de dojo.

Ordered by where you meet the word, not alphabetically: the dojo first, then
what you say, then who is who, then the practice itself.
"""

CATS = [
    ('dojo', 'En el dojo', 'El espacio y lo que hay en él', [
        ('道場', 'dōjō', 'El lugar donde se estudia el camino. No es un gimnasio: se entra y se sale saludando.'),
        ('畳', 'tatami', 'La estera sobre la que se practica. Da nombre al suelo entero, aunque hoy sea de otro material.'),
        ('正面', 'shōmen', 'El frente del dojo, donde cuelgan la caligrafía y el retrato del fundador. Se saluda hacia allí.'),
        ('上座', 'kamiza', 'El lado de honor del dojo, junto al shōmen.'),
        ('下座', 'shimoza', 'El lado opuesto al kamiza, donde se sitúan los estudiantes.'),
        ('道場長', 'dōjō-chō', 'El responsable del dojo. En Aikido Musubi, Pablo Martín.'),
        ('掃除', 'sōji', 'La limpieza del dojo. La hacen los estudiantes y forma parte de la práctica.'),
        ('更衣室', 'kōishitsu', 'El vestuario.'),
    ]),
    ('frases', 'Saludos y frases', 'Lo que se dice en voz alta', [
        ('礼', 'rei', 'El saludo. Abre y cierra la clase, y también cada práctica con cada compañero.'),
        ('お願いします', 'onegaishimasu', '«Te lo pido, por favor.» Se le dice al compañero antes de practicar con él.'),
        ('ありがとうございました', 'arigatō gozaimashita', '«Muchas gracias.» Se le dice al terminar.'),
        ('正座', 'seiza', 'Sentarse sobre los talones. Así empieza y termina cada clase.'),
        ('黙想', 'mokusō', 'Un momento breve de silencio con los ojos cerrados, antes o después de la clase.'),
        ('始め', 'hajime', '«Empezad.»'),
        ('止め', 'yame', '«Parad.»'),
        ('交代', 'kōtai', '«Cambiad»: de papel o de compañero.'),
        ('どうぞ', 'dōzo', '«Adelante», «por favor, pasa».'),
        ('失礼します', 'shitsurei shimasu', '«Disculpe la molestia.» Se dice al entrar o salir del tatami fuera de tiempo.'),
        ('すみません', 'sumimasen', '«Perdón», «disculpe».'),
        ('はい', 'hai', '«Sí», y también «entendido».'),
    ]),
    ('gente', 'Quién es quién', 'Personas, títulos y grados', [
        ('先生', 'sensei', '«El que nació antes.» El que enseña.'),
        ('師範', 'shihan', '«Modelo a seguir.» Título de la Aikikai para los maestros de grado alto.'),
        ('指導員', 'shidōin', 'Instructor titulado por la Aikikai. El título de Pablo Martín.'),
        ('副指導員', 'fukushidōin', 'Instructor auxiliar titulado, un escalón por debajo de shidōin.'),
        ('道主', 'dōshu', '«El dueño del camino.» El jefe de la escuela; hoy Ueshiba Moriteru.'),
        ('開祖', 'kaiso', 'El fundador. Para el aikido, Morihei Ueshiba.'),
        ('翁先生', 'Ō-Sensei', '«Gran maestro.» Como se llama a Ueshiba dentro del dojo.'),
        ('先輩', 'senpai', 'Quien lleva más tiempo practicando que tú.'),
        ('後輩', 'kōhai', 'Quien lleva menos.'),
        ('内弟子', 'uchideshi', 'Alumno que vive en el dojo y lo atiende a cambio de la enseñanza.'),
        ('級', 'kyū', 'Los grados anteriores al cinturón negro. Se numeran a la baja: 5.º, 4.º, 3.º…'),
        ('段', 'dan', 'Los grados a partir del cinturón negro. Se numeran al alza.'),
        ('有段者', 'yūdansha', 'Quien ya tiene grado dan.'),
        ('審査', 'shinsa', 'El examen de grado.'),
    ]),
    ('ropa', 'Ropa y armas', 'Lo que se lleva y lo que se coge', [
        ('稽古着', 'keikogi', 'La ropa de práctica. Para las primeras clases basta con manga larga.'),
        ('帯', 'obi', 'El cinturón.'),
        ('袴', 'hakama', 'El pantalón ancho plisado. En muchos dojos lo visten los grados dan.'),
        ('草履', 'zōri', 'Las sandalias para ir del vestuario al borde del tatami. En el tatami se entra descalzo.'),
        ('木刀', 'bokken', 'El sable de madera.'),
        ('杖', 'jō', 'El bastón de madera, de metro y pico.'),
        ('短刀', 'tantō', 'El cuchillo de madera, para las técnicas de desarme.'),
        ('武器', 'buki', 'Las armas, en general.'),
    ]),
    ('cuerpo', 'Cuerpo y movimiento', 'Cómo se mueve uno', [
        ('受身', 'ukemi', 'La caída. La mitad del aikido consiste en aprender a recibir sin romperse.'),
        ('体捌き', 'tai sabaki', 'El desplazamiento del cuerpo para salir de la línea del ataque.'),
        ('入身', 'irimi', 'Entrar. Ocupar el espacio del atacante en lugar de retroceder.'),
        ('転換', 'tenkan', 'Girar sobre el pie adelantado para acompañar la fuerza en vez de chocar con ella.'),
        ('表・裏', 'omote / ura', 'Las dos versiones de casi toda técnica: la que entra por delante y la que gira por detrás.'),
        ('間合い', 'ma-ai', 'La distancia justa entre dos personas. Ni tan cerca que estorbe ni tan lejos que no llegue.'),
        ('残心', 'zanshin', 'La atención que queda después de terminar. La técnica no acaba cuando el otro cae.'),
        ('呼吸', 'kokyū', 'La respiración, y por extensión el tiempo interior del movimiento.'),
        ('丹田', 'tanden', 'El centro, dos dedos bajo el ombligo. De ahí sale el movimiento.'),
        ('構え', 'kamae', 'La postura de guardia.'),
        ('半身', 'hanmi', 'El cuerpo de perfil, un pie adelantado. La postura básica.'),
        ('膝行', 'shikkō', 'Caminar de rodillas.'),
        ('座り技', 'suwariwaza', 'Técnicas con los dos de rodillas.'),
        ('半身半立', 'hanmi handachi', 'Uno de rodillas y el otro de pie.'),
        ('立ち技', 'tachiwaza', 'Técnicas de pie.'),
        ('後ろ技', 'ushirowaza', 'Técnicas contra ataques por la espalda.'),
        ('取り・受け', 'tori / uke', 'Quien hace la técnica y quien la recibe. Se alternan sin parar.'),
    ]),
    ('ataques', 'Ataques', 'Cómo empieza cada técnica', [
        ('正面打ち', 'shōmen uchi', 'Corte vertical a la cabeza.'),
        ('横面打ち', 'yokomen uchi', 'Corte diagonal a la sien.'),
        ('突き', 'tsuki', 'Golpe directo, normalmente al abdomen.'),
        ('片手取り', 'katate dori', 'Agarre de una muñeca con una mano.'),
        ('諸手取り', 'morote dori', 'Agarre de una muñeca con las dos manos.'),
        ('両手取り', 'ryōte dori', 'Agarre de las dos muñecas.'),
        ('肩取り', 'kata dori', 'Agarre del hombro.'),
        ('胸取り', 'mune dori', 'Agarre de la solapa.'),
        ('後ろ両手取り', 'ushiro ryōte dori', 'Agarre de las dos muñecas por detrás.'),
    ]),
    ('tecnicas', 'Técnicas', 'Las que más se oyen', [
        ('一教', 'ikkyō', '«Primera enseñanza.» Control del codo.'),
        ('二教', 'nikyō', '«Segunda.» Torsión de la muñeca hacia dentro.'),
        ('三教', 'sankyō', '«Tercera.» Torsión en espiral del brazo.'),
        ('四教', 'yonkyō', '«Cuarta.» Presión sobre el nervio del antebrazo.'),
        ('五教', 'gokyō', '«Quinta.» Variante de ikkyō para el desarme del cuchillo.'),
        ('入身投げ', 'irimi nage', '«Proyección entrando.»'),
        ('四方投げ', 'shihō nage', '«Proyección a las cuatro direcciones.»'),
        ('小手返し', 'kote gaeshi', '«Vuelta de muñeca.»'),
        ('回転投げ', 'kaiten nage', '«Proyección giratoria.»'),
        ('天地投げ', 'tenchi nage', '«Proyección cielo y tierra.»'),
        ('腰投げ', 'koshi nage', 'Proyección de cadera.'),
        ('呼吸法', 'kokyū hō', 'El ejercicio de respiración con el que suele cerrarse la clase.'),
        ('抑え技', 'osaewaza', 'Técnicas de control en el suelo.'),
        ('投げ技', 'nagewaza', 'Técnicas de proyección.'),
    ]),
    ('ideas', 'Ideas', 'Lo que hay detrás de todo lo demás', [
        ('合気道', 'aikidō', '«El camino de la unión con la energía.»'),
        ('合気', 'aiki', 'Unir la propia energía con la del otro en vez de oponerse a ella.'),
        ('気', 'ki', 'La energía, el aliento, la intención. La misma sílaba que abre aikidō.'),
        ('武道', 'budō', '«La vía marcial.» Las artes marciales entendidas como camino, no como deporte.'),
        ('道', 'dō', 'El camino. La misma palabra que en aikidō, judō o karatedō.'),
        ('稽古', 'keiko', 'La práctica. Literalmente «pensar en lo antiguo»: se repite algo que otros repitieron antes.'),
        ('修行', 'shugyō', 'La práctica sostenida durante años, con todo lo que implica.'),
        ('型', 'kata', 'La forma fija que se repite para aprenderla.'),
        ('乱取り', 'randori', 'Práctica libre contra varios atacantes.'),
        ('自由技', 'jiyū waza', 'Técnica libre: el ataque está fijado, la respuesta no.'),
        ('気合', 'kiai', 'El grito que acompaña un movimiento decidido.'),
        ('無心', 'mushin', '«Sin mente.» Actuar sin que el pensamiento se interponga.'),
        ('初心', 'shoshin', '«Mente de principiante.» La disposición que conviene conservar siempre.'),
        ('礼法', 'reihō', 'La etiqueta del dojo: cómo se entra, cómo se saluda, cómo se trata al compañero.'),
        ('産靈', 'musubi', 'El nudo: lo que une dos cosas y las deja unidas. De ahí el nombre del dojo.'),
    ]),
    ('casa', 'Frases de la casa', 'Las que están escritas en nuestras paredes', [
        ('唱えよ、友、そして入れ。', 'tonaeyo, tomo, soshite haire',
         '«Habla, amigo, y entra.» Está a la entrada de nuestro tatami. Viene de la puerta de '
         'Moria, en <em>El Señor de los Anillos</em>: la contraseña era decir «amigo» en élfico.'),
        ('見つけて壊せ。', 'mitsukete kowase',
         '«Búscalo y destrúyelo.» Seek & Destroy.'),
        ('形無くして、無定形、水のように。', 'katachi nakushite, muteikei, mizu no yō ni',
         '«Sin forma, sin figura, como el agua.» De Bruce Lee, y una descripción bastante '
         'exacta de lo que se busca en el tenkan.'),
        ('我らの道。', 'warera no michi',
         '«Este es el camino.» De <em>The Mandalorian</em>. En el dojo se dice medio en broma '
         'y medio en serio, que es como se dicen las cosas importantes.'),
    ]),
    ('kaiju', 'Kaijū', 'Monstruos gigantes, que también son cultura japonesa', [
        ('ゴジラ', 'Gojira', 'Godzilla. El nombre sale de juntar <em>gorira</em> (gorila) y '
         '<em>kujira</em> (ballena). Vive en nuestra página de error 404.'),
        ('怪獣', 'kaijū', '«Bestia extraña.» El género entero de monstruos gigantes.'),
        ('大怪獣', 'daikaijū', 'El kaijū grande, el que da nombre a la película.'),
        ('特撮', 'tokusatsu', '«Fotografía especial.» El cine japonés de efectos prácticos: '
         'trajes de goma, maquetas y ciudades en miniatura.'),
        ('着ぐるみ', 'kigurumi', 'El traje de monstruo con actor dentro. La técnica que hizo '
         'posible el género.'),
        ('東宝', 'Tōhō', 'El estudio que produjo <em>Gojira</em> en 1954 y casi todo lo que vino '
         'después.'),
        ('放射熱線', 'hōshanetsusen', '«Rayo térmico radiactivo.» El aliento atómico.'),
        ('モスラ', 'Mosura', 'Mothra. La polilla gigante, y la única kaijū claramente benévola.'),
        ('ラドン', 'Radon', 'Rodan. El pteranodonte.'),
        ('キングギドラ', 'Kingu Gidora', 'King Ghidora. El dragón de tres cabezas.'),
        ('ウルトラマン', 'Urutoraman', 'Ultraman. El gigante de plata que pelea con los kaijū '
         'cada semana desde 1966.'),
        ('破壊', 'hakai', 'Destrucción. Lo que le pasa a Tokio, y a esta página.'),
    ]),
    ('contar', 'Contar', 'Del uno al diez, que se oye cada día', [
        ('一', 'ichi', 'Uno.'), ('二', 'ni', 'Dos.'), ('三', 'san', 'Tres.'),
        ('四', 'shi / yon', 'Cuatro. Al contar en el dojo se suele decir «shi».'),
        ('五', 'go', 'Cinco.'), ('六', 'roku', 'Seis.'),
        ('七', 'shichi / nana', 'Siete.'), ('八', 'hachi', 'Ocho.'),
        ('九', 'kyū / ku', 'Nueve. Suena igual que el grado kyū.'), ('十', 'jū', 'Diez.'),
    ]),
]

TOTAL = sum(len(c[3]) for c in CATS)
